name: UnitTest

on: [push, pull_request]

jobs:
  UnitTest:
    name: UnitTest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -e erniebot-agent/
          python -m pip install -r tests/requirements.txt
      - name: Run the command
        run: pytest tests/unit_test
